aibs_metamodel_celltypes_v661:
  L1:   [NGC, BPC, MC, BC]
  L2/3: [23P]
  L4:   [4P]
  L5:   [5P-IT, 5P-ET, 5P-NP]
  L6:   [6P-IT, 6P-CT]
  WM:   [Oligo, OPC, Pericyte]

cell_type_multifeature_combo:
  L1:   [L1, NGC, MC]
  L2/3: [L2IT, L3IT]
  L4:   [L4IT]
  L5:   [L5IT, L5ET, L5NP]
  L6:   [L6IT, L6CT]
  WM:   []